import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Calculator, CircleDollarSign, RefreshCw, ShieldCheck } from 'lucide-react';
import { adminFinancialSummary, createCommissionRule, getOrderFinancials, listCommissionRules, reconcileCommission, setCommissionRuleStatus, simulateCommission, updateCommissionRule, type CommissionRule } from '../lib/commerce';
import { notifyToast } from '../lib/toast';

const inr=(value:number)=>`₹${Number(value||0).toLocaleString('en-IN',{minimumFractionDigits:0,maximumFractionDigits:2})}`;
const initial={scope:'global',productId:'',creatorId:'',percentage:'10',fixedAmount:'0',minimumAmount:'',maximumAmount:'',currency:'INR',effectiveFrom:'',effectiveUntil:'',priority:'0'};

export const CommissionAdminPanel: React.FC = () => {
  const [rules,setRules]=useState<CommissionRule[]>([]);
  const [loading,setLoading]=useState(false);
  const [form,setForm]=useState<any>(initial);
  const [editingRuleId,setEditingRuleId]=useState('');
  const [sim,setSim]=useState<any>({grossAmount:'1000',percentage:'10',fixedAmount:'0',ruleId:''});
  const [simResult,setSimResult]=useState<any>(null);
  const [summary,setSummary]=useState<any>(null);
  const [summaryRange,setSummaryRange]=useState<'all'|'today'|'7d'|'30d'>('all');
  const [orderId,setOrderId]=useState('');
  const [orderFinancials,setOrderFinancials]=useState<any>(null);
  const [busyOrder,setBusyOrder]=useState(false);
  const load=useCallback(async()=>{setLoading(true);try{const [r,s]=await Promise.all([listCommissionRules(),adminFinancialSummary(summaryRange==='all'?{}:{range:summaryRange})]);setRules(r.rules||[]);setSummary(s);}catch(e:any){notifyToast(e?.message||'Commission data unavailable.','error');}finally{setLoading(false);}},[summaryRange]);
  useEffect(()=>{void load();},[load]);
  const visibleRules=useMemo(()=>[...rules].sort((a,b)=>b.ruleVersion-a.ruleVersion||b.priority-a.priority),[rules]);
  const update=(k:string,v:string)=>setForm((p:any)=>({...p,[k]:v}));
  const submitRule=async()=>{try{const payload:any={scope:form.scope,productId:form.productId||undefined,creatorId:form.creatorId||undefined,percentage:form.percentage===''?undefined:Number(form.percentage),fixedAmount:form.fixedAmount===''?undefined:Number(form.fixedAmount),minimumAmount:form.minimumAmount===''?undefined:Number(form.minimumAmount),maximumAmount:form.maximumAmount===''?undefined:Number(form.maximumAmount),currency:'INR',effectiveFrom:form.effectiveFrom||undefined,effectiveUntil:form.effectiveUntil||undefined,priority:Number(form.priority||0),active:true,refundPolicy:{proportional:true}};if(editingRuleId){payload.ruleId=editingRuleId;await updateCommissionRule(payload);notifyToast('New commission rule version created.','success');}else{await createCommissionRule(payload);notifyToast('Commission rule created.','success');}setForm(initial);setEditingRuleId('');await load();}catch(e:any){notifyToast(e?.message||'Commission rule save failed.','error');}};
  const edit=(rule:CommissionRule)=>{setEditingRuleId(rule.ruleId);setForm({scope:rule.scope,productId:rule.productId||'',creatorId:rule.creatorId||'',percentage:String(rule.percentage),fixedAmount:String(rule.fixedAmount),minimumAmount:rule.minimumAmount===undefined?'':String(rule.minimumAmount),maximumAmount:rule.maximumAmount===undefined?'':String(rule.maximumAmount),currency:'INR',effectiveFrom:rule.effectiveFrom,effectiveUntil:rule.effectiveUntil||'',priority:String(rule.priority)});};
  const runSim=async()=>{try{setSimResult(await simulateCommission({grossAmount:Number(sim.grossAmount),ruleId:sim.ruleId||undefined,scope:'global',percentage:sim.percentage===''?undefined:Number(sim.percentage),fixedAmount:sim.fixedAmount===''?undefined:Number(sim.fixedAmount),currency:'INR'}));}catch(e:any){notifyToast(e?.message||'Simulation failed.','error');}};
  const lookupOrder=async()=>{if(!orderId.trim())return;setBusyOrder(true);try{setOrderFinancials(await getOrderFinancials(orderId.trim()));}catch(e:any){notifyToast(e?.message||'Order financials unavailable.','error');setOrderFinancials(null);}finally{setBusyOrder(false);}};
  const reconcile=async()=>{if(!orderId.trim())return;try{await reconcileCommission(orderId.trim());notifyToast('Commission reconciliation completed.','success');await lookupOrder();await load();}catch(e:any){notifyToast(e?.message||'Reconciliation failed.','error');}};
  return <section className="space-y-4">
    <div className="border-4 border-black bg-black text-white p-5 neo-shadow-lg"><div className="font-mono text-[10px] text-[var(--color-primary)] font-black uppercase flex items-center gap-2"><CircleDollarSign className="w-4 h-4"/> V93 · FINANCE</div><h2 className="font-display font-black text-3xl sm:text-4xl uppercase mt-2">Commission + Profit-Cut</h2><p className="text-sm text-neutral-300 mt-2 max-w-3xl">Server-authoritative commission rules and transaction allocations. No creator balance or Route payout is executed here.</p></div>
    <div className="grid sm:grid-cols-3 gap-3">{[[`GROSS · ${summaryRange.toUpperCase()}`,summary?.grossSales],['OFFSCRPT COMMISSION',summary?.platformCommission],['CREATOR NET',summary?.creatorNet],['REFUNDED',summary?.refundedAmount],['FINANCE ERRORS',summary?.financialErrors]].map(([label,value])=><div key={String(label)} className="border-2 border-black bg-white p-4"><div className="font-mono text-[8px] font-black uppercase">{label}</div><div className="font-display font-black text-3xl mt-2">{summary&&typeof value==='number'?inr(value):'—'}</div></div>)}</div>
    <div className="flex flex-wrap items-center gap-2"><button onClick={()=>void load()} className="border-2 border-black bg-white px-3 py-2 font-mono text-[9px] font-black uppercase"><RefreshCw className="inline w-3 h-3 mr-1"/>{loading?'LOADING':'REFRESH'}</button><select value={summaryRange} onChange={e=>setSummaryRange(e.target.value as any)} className="border-2 border-black bg-white px-3 py-2 font-mono text-[9px] font-black uppercase"><option value="all">ALL TIME</option><option value="today">TODAY</option><option value="7d">7 DAYS</option><option value="30d">30 DAYS</option></select><span className="border-2 border-black bg-[var(--color-primary)] px-3 py-2 font-mono text-[9px] font-black uppercase"><ShieldCheck className="inline w-3 h-3 mr-1"/>SERVER-AUTHORITATIVE</span></div>

    <div className="border-2 border-black bg-white p-5 space-y-3"><div className="font-display font-black text-2xl uppercase">COMMISSION RULE {editingRuleId?'VERSION UPDATE':'CREATOR'}</div><div className="grid md:grid-cols-3 gap-2"><select value={form.scope} onChange={e=>update('scope',e.target.value)} className="border-2 border-black p-3 font-mono text-xs"><option value="global">Global</option><option value="creator">Creator</option><option value="product">Product</option></select><input value={form.creatorId} onChange={e=>update('creatorId',e.target.value)} placeholder="Creator ID (creator scope)" className="border-2 border-black p-3 font-mono text-xs" disabled={form.scope!=='creator'}/><input value={form.productId} onChange={e=>update('productId',e.target.value)} placeholder="Product ID (product scope)" className="border-2 border-black p-3 font-mono text-xs" disabled={form.scope!=='product'}/><input value={form.percentage} onChange={e=>update('percentage',e.target.value)} placeholder="Percentage (e.g. 10)" className="border-2 border-black p-3 font-mono text-xs" inputMode="decimal"/><input value={form.fixedAmount} onChange={e=>update('fixedAmount',e.target.value)} placeholder="Fixed INR amount" className="border-2 border-black p-3 font-mono text-xs" inputMode="numeric"/><input value={form.priority} onChange={e=>update('priority',e.target.value)} placeholder="Priority" className="border-2 border-black p-3 font-mono text-xs" inputMode="numeric"/><input value={form.minimumAmount} onChange={e=>update('minimumAmount',e.target.value)} placeholder="Minimum commission (optional)" className="border-2 border-black p-3 font-mono text-xs" inputMode="numeric"/><input value={form.maximumAmount} onChange={e=>update('maximumAmount',e.target.value)} placeholder="Maximum commission (optional)" className="border-2 border-black p-3 font-mono text-xs" inputMode="numeric"/><input type="datetime-local" value={form.effectiveFrom} onChange={e=>update('effectiveFrom',e.target.value)} className="border-2 border-black p-3 font-mono text-xs"/></div><div className="font-mono text-[9px] text-neutral-600">A rule is versioned when edited. Historical transactions keep their original rule snapshot. Empty fixed/percentage components are ignored; explicit 0% is valid.</div><div className="flex gap-2"><button onClick={()=>void submitRule()} className="border-2 border-black bg-[var(--color-primary)] px-4 py-3 font-mono text-[9px] font-black uppercase">{editingRuleId?'CREATE NEW VERSION':'CREATE RULE'}</button>{editingRuleId&&<button onClick={()=>{setEditingRuleId('');setForm(initial);}} className="border-2 border-black bg-white px-4 py-3 font-mono text-[9px] font-black uppercase">CANCEL</button>}</div></div>

    <div className="border-2 border-black bg-white p-5"><div className="flex items-center justify-between gap-3 mb-3"><div className="font-display font-black text-2xl uppercase">RULE HISTORY</div><span className="font-mono text-[9px]">{visibleRules.length} RECORDS</span></div><div className="overflow-x-auto"><table className="min-w-[1100px] w-full border-collapse text-left"><thead><tr className="bg-black text-white font-mono text-[8px] font-black uppercase">{['Rule','Scope','Version','Rate','Fixed','Priority','Effective','Status','Actions'].map(h=><th key={h} className="p-2 border-r border-white">{h}</th>)}</tr></thead><tbody>{visibleRules.map(r=>{const latest=visibleRules.filter(x=>x.ruleId===r.ruleId).sort((a,b)=>b.ruleVersion-a.ruleVersion)[0]; const isLatest=latest?.id===r.id; return <tr key={r.id} className="border-t-2 border-black font-mono text-[9px]"><td className="p-2">{r.ruleId}</td><td className="p-2">{r.scope}</td><td className="p-2">v{r.ruleVersion}</td><td className="p-2">{r.percentage}%</td><td className="p-2">{inr(r.fixedAmount)}</td><td className="p-2">{r.priority}</td><td className="p-2">{new Date(r.effectiveFrom).toLocaleString()}</td><td className="p-2">{r.active?'ACTIVE':'INACTIVE'}</td><td className="p-2"><div className="flex gap-1">{isLatest?<><button onClick={()=>edit(r)} className="border-2 border-black px-2 py-1 font-black">VERSION</button><button onClick={()=>void setCommissionRuleStatus(r.ruleId,!r.active).then(()=>load()).catch(e=>notifyToast(e?.message||'Rule status update failed.','error'))} className="border-2 border-black px-2 py-1 font-black">{r.active?'DISABLE':'ACTIVATE'}</button></>:<span className="px-2 py-1 text-neutral-500">HISTORICAL</span>}</div></td></tr>})}{!visibleRules.length&&<tr><td colSpan={9} className="p-6 text-center font-mono text-xs">NO COMMISSION RULES CONFIGURED.</td></tr>}</tbody></table></div></div>

    <div className="border-2 border-black bg-white p-5 space-y-3"><div className="font-display font-black text-2xl uppercase flex items-center gap-2"><Calculator className="w-5 h-5"/> COMMISSION SIMULATOR</div><div className="grid md:grid-cols-4 gap-2"><input value={sim.grossAmount} onChange={e=>setSim((p:any)=>({...p,grossAmount:e.target.value}))} placeholder="Gross INR" className="border-2 border-black p-3 font-mono text-xs" inputMode="numeric"/><input value={sim.percentage} onChange={e=>setSim((p:any)=>({...p,percentage:e.target.value}))} placeholder="Ad-hoc %" className="border-2 border-black p-3 font-mono text-xs" inputMode="decimal"/><input value={sim.fixedAmount} onChange={e=>setSim((p:any)=>({...p,fixedAmount:e.target.value}))} placeholder="Ad-hoc fixed INR" className="border-2 border-black p-3 font-mono text-xs" inputMode="numeric"/><select value={sim.ruleId} onChange={e=>setSim((p:any)=>({...p,ruleId:e.target.value}))} className="border-2 border-black p-3 font-mono text-xs"><option value="">Use ad-hoc 10% simulation</option>{visibleRules.filter(r=>r.active).map(r=><option key={r.id} value={r.ruleId}>{r.ruleId} · v{r.ruleVersion} · {r.percentage}%</option>)}</select><button onClick={()=>void runSim()} className="border-2 border-black bg-black text-white px-4 py-3 font-mono text-[9px] font-black uppercase">CALCULATE</button></div>{simResult&&<div className="grid sm:grid-cols-3 gap-2"><div className="border-2 border-black p-3"><div className="font-mono text-[8px]">GROSS</div><div className="font-display font-black text-2xl mt-1">{inr(simResult.result.grossAmount)}</div></div><div className="border-2 border-black p-3"><div className="font-mono text-[8px]">COMMISSION</div><div className="font-display font-black text-2xl mt-1">{inr(simResult.result.platformCommissionAmount)}</div></div><div className="border-2 border-black p-3"><div className="font-mono text-[8px]">CREATOR NET</div><div className="font-display font-black text-2xl mt-1">{inr(simResult.result.creatorNetAmount)}</div></div></div>}</div>

    <div className="border-2 border-black bg-white p-5 space-y-3"><div className="font-display font-black text-2xl uppercase">ORDER FINANCIAL LOOKUP</div><div className="flex gap-2"><input value={orderId} onChange={e=>setOrderId(e.target.value)} placeholder="OFFSCRPT order ID" className="flex-1 border-2 border-black p-3 font-mono text-xs"/><button onClick={()=>void lookupOrder()} disabled={busyOrder} className="border-2 border-black bg-white px-4 py-3 font-mono text-[9px] font-black uppercase">{busyOrder?'LOOKING…':'LOOKUP'}</button></div>{orderFinancials&&<div className="space-y-2"><div className="grid md:grid-cols-4 gap-2 font-mono text-[9px]"><div className="border-2 border-black p-3">ORDER<br/><b>{orderFinancials.order.status}</b></div><div className="border-2 border-black p-3">FINANCE<br/><b>{orderFinancials.allocation?.financialStatus||'NOT CREATED'}</b></div><div className="border-2 border-black p-3">GROSS<br/><b>{orderFinancials.allocation?inr(orderFinancials.allocation.grossAmount):'—'}</b></div><div className="border-2 border-black p-3">CREATOR NET<br/><b>{orderFinancials.allocation?.creatorNetAmount!=null?inr(orderFinancials.allocation.creatorNetAmount):'—'}</b></div></div>{orderFinancials.allocation?.financialStatus==='reconciliation_required'&&<button onClick={()=>void reconcile()} className="border-2 border-black bg-[var(--color-primary)] px-4 py-2 font-mono text-[9px] font-black uppercase">RECONCILE COMMISSION</button>}<pre className="border-2 border-black bg-neutral-100 p-3 overflow-auto text-[8px] max-h-60">{JSON.stringify(orderFinancials,null,2)}</pre></div>}</div>
  </section>;
};
