import React, { useEffect, useState } from 'react';
import { CheckCircle2, LockKeyhole, RefreshCw, ShieldCheck, Store, WalletCards } from 'lucide-react';
import type { CommunityUser } from '../types';
import { createCreatorSeller, disableCreatorSeller, enableCreatorSeller, getCreatorSeller, refreshCreatorSeller, type CreatorSellerProfile, type SellerOnboardingInput } from '../lib/commerce';
import { notifyToast } from '../lib/toast';

interface Props { userProfile: CommunityUser | null; }
const initial=(u:CommunityUser):SellerOnboardingInput=>({email:u.email||'',phone:'',upiId:'',legalBusinessName:u.displayName||'',customerFacingBusinessName:u.displayName||'',businessType:'individual',contactName:u.displayName||'',category:'digital_goods',subcategory:'digital_products',description:'Digital products sold through OFFSCRPT.',street1:'',street2:'',city:'',state:'',postalCode:''});
const stateLabel=(s:string)=>({not_started:'SETUP REQUIRED',collecting_information:'INFORMATION REQUIRED',creating_account:'CREATING ACCOUNT',created:'DETAILS SAVED',pending_review:'PENDING REVIEW',active:'ACTIVE',suspended:'SUSPENDED',rejected:'REJECTED',error:'ERROR',reconciliation_required:'RECONCILIATION REQUIRED'} as Record<string,string>)[s]||s.toUpperCase();
export const CreatorSellerOnboardingPanel: React.FC<Props> = ({userProfile}) => {
 const [seller,setSeller]=useState<CreatorSellerProfile|null>(null); const [form,setForm]=useState<SellerOnboardingInput|null>(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState('');
 const load=async()=>{if(!userProfile)return;setLoading(true);try{const r=await getCreatorSeller();setSeller(r.seller);setForm(prev=>prev||{...initial(userProfile),email:r.seller.email||userProfile.email||'',phone:r.seller.phone||'',upiId:r.seller.manualPayout?.upiId||r.seller.upiId||'',legalBusinessName:r.seller.legalBusinessName||userProfile.displayName||'',customerFacingBusinessName:r.seller.customerFacingBusinessName||userProfile.displayName||'',businessType:r.seller.businessType||'individual',contactName:userProfile.displayName||''});}catch(e:any){setNotice(e?.message||'Seller data unavailable.');}finally{setLoading(false);}};
 useEffect(()=>{void load();},[userProfile?.uid]);
 if(!userProfile)return null;
 const update=(key:keyof SellerOnboardingInput,value:string)=>setForm(prev=>prev?({...prev,[key]:value}):prev);
 const submit=async()=>{if(!form)return;setBusy(true);setNotice('');try{const r=await createCreatorSeller(form);setSeller(r.seller);setNotice(r.message||'Manual payout details saved.');notifyToast('Seller payout profile saved.','success');}catch(e:any){setNotice(e?.message||'Could not save payout profile.');notifyToast(e?.message||'Could not save payout profile.','error');}finally{setBusy(false);}};
 const enable=async()=>{setBusy(true);try{const r=await enableCreatorSeller();setSeller(r.seller);setNotice('Selling is enabled. Customer payments will be collected by OFFSCRPT and creator payouts will be handled manually.');}catch(e:any){setNotice(e?.message||'Could not enable selling.');}finally{setBusy(false);}};
 const disable=async()=>{setBusy(true);try{const r=await disableCreatorSeller();setSeller(r.seller);setNotice('Selling disabled. Payout details are preserved.');}catch(e:any){setNotice(e?.message||'Could not disable selling.');}finally{setBusy(false);}};
 const detailsReady=Boolean(form?.upiId&&form?.phone&&form?.email);
 return <section className="space-y-4">
  <div className="border-4 border-black bg-[var(--color-primary)] p-5 neo-shadow"><div className="flex items-center gap-2 font-mono text-[10px] font-black uppercase"><Store className="w-4 h-4"/> MANUAL SELLER PAYOUTS</div><h2 className="font-display font-black text-3xl sm:text-4xl uppercase mt-2">Creator Selling</h2><p className="font-mono text-[10px] mt-2 max-w-3xl">Razorpay Route transfers are disabled for this marketplace configuration. Customer checkout payments go to OFFSCRPT. Creator earnings remain tracked in the canonical V94 ledger and are paid manually by admin.</p></div>
  <div className="border-2 border-black bg-white p-5"><div className="flex flex-wrap justify-between gap-3 items-start"><div><div className="font-mono text-[9px] font-black uppercase">SELLER STATUS</div><div className="font-display font-black text-2xl uppercase mt-1">{loading?'LOADING…':stateLabel(seller?.onboardingStatus||'not_started')}</div><div className="font-mono text-[9px] mt-2">PAYOUT MODE · MANUAL UPI</div></div><div className="flex flex-wrap gap-2"><button onClick={()=>void load()} disabled={busy||loading} className="border-2 border-black px-3 py-2 font-mono text-[9px] font-black uppercase"><RefreshCw className="inline w-3 h-3 mr-1"/>REFRESH</button>{seller?.sellerEnabled&&<button onClick={()=>void disable()} disabled={busy} className="border-2 border-black px-3 py-2 font-mono text-[9px] font-black uppercase">DISABLE SELLING</button>}</div></div><div className="grid sm:grid-cols-3 gap-2 mt-4"><div className="border-2 border-black p-3"><div className="font-mono text-[8px]">UPI ID</div><div className="font-mono text-[10px] font-black mt-1 break-all">{seller?.manualPayout?.upiId||seller?.upiId||'—'}</div></div><div className="border-2 border-black p-3"><div className="font-mono text-[8px]">MOBILE</div><div className="font-mono text-[10px] font-black mt-1">{seller?.manualPayout?.mobile||seller?.phone||'—'}</div></div><div className="border-2 border-black p-3"><div className="font-mono text-[8px]">EMAIL</div><div className="font-mono text-[10px] font-black mt-1 break-all">{seller?.manualPayout?.email||seller?.email||'—'}</div></div></div></div>
  <div className="border-2 border-black bg-white p-5 space-y-3"><div className="flex items-center gap-2 font-display font-black uppercase text-xl"><WalletCards className="w-5 h-5"/> Manual payout details</div><div className="font-mono text-[9px] text-neutral-600">Provide the UPI ID, mobile number and email where you can receive manual creator repayments. These details are stored on the private seller profile and shown to authorized admins for payout settlement. Do not enter a UPI PIN, password or card information.</div><div className="grid md:grid-cols-3 gap-2"><input value={form?.email||''} onChange={e=>update('email',e.target.value)} placeholder="Email" className="border-2 border-black p-3 font-mono text-xs" inputMode="email"/><input value={form?.phone||''} onChange={e=>update('phone',e.target.value)} placeholder="Mobile number" className="border-2 border-black p-3 font-mono text-xs" inputMode="tel"/><input value={form?.upiId||''} onChange={e=>update('upiId',e.target.value)} placeholder="UPI ID e.g. name@upi" className="border-2 border-black p-3 font-mono text-xs" autoCapitalize="none"/></div><div className="grid md:grid-cols-2 gap-2"><input value={form?.legalBusinessName||''} onChange={e=>update('legalBusinessName',e.target.value)} placeholder="Creator / business name" className="border-2 border-black p-3 font-mono text-xs"/><input value={form?.customerFacingBusinessName||''} onChange={e=>update('customerFacingBusinessName',e.target.value)} placeholder="Customer-facing name" className="border-2 border-black p-3 font-mono text-xs"/></div><button disabled={busy||loading||!detailsReady} onClick={()=>void submit()} className="w-full border-2 border-black bg-black text-white px-4 py-3 font-mono text-[10px] font-black uppercase disabled:opacity-40">{busy?'SAVING…':'SAVE PAYOUT DETAILS'}</button></div>
  {!seller?.sellerEnabled&&seller&&detailsReady&&<div className="border-2 border-black bg-white p-5"><div className="flex items-center gap-2 font-display font-black uppercase text-xl"><ShieldCheck className="w-5 h-5"/> SELLING READINESS</div><p className="font-mono text-[9px] mt-2 text-neutral-600">Once the payout profile is complete, enable selling. Customer payments will remain with OFFSCRPT and creator payouts will be tracked for manual settlement.</p><button disabled={busy} onClick={()=>void enable()} className="mt-4 border-2 border-black bg-[var(--color-primary)] px-4 py-3 font-mono text-[10px] font-black uppercase">ENABLE SELLING</button></div>}
  {seller?.sellerEnabled&&<div className="border-2 border-black bg-[var(--color-primary)] p-5 flex items-center gap-3"><CheckCircle2 className="w-6 h-6"/><div><div className="font-display font-black uppercase text-xl">SELLING ENABLED</div><div className="font-mono text-[9px] mt-1">Checkout payments are collected by OFFSCRPT. Creator balances are paid manually by admin.</div></div></div>}
  {notice&&<div className="border-2 border-black bg-yellow-100 p-3 font-mono text-[9px] font-black">{notice}</div>}
  <div className="border-2 border-black bg-white p-4 font-mono text-[9px] flex gap-2 items-start"><LockKeyhole className="w-4 h-4 shrink-0"/><div>Razorpay Route transfers are disabled. OFFSCRPT stores only the creator's payout contact details required for manual repayment. Never submit UPI PINs, banking passwords or card credentials.</div></div>
 </section>;
};
