import React, { useCallback, useEffect, useState } from 'react';
import { CircleDollarSign, RefreshCw, ShieldCheck, Wallet } from 'lucide-react';
import { createCreatorPayout, getCreatorBalance, getCreatorPayouts, type CreatorBalanceSummary, type CreatorPayout } from '../lib/commerce';
import { notifyToast } from '../lib/toast';

const inr=(paise:number)=>`₹${(Number(paise||0)/100).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;

export const CreatorPayoutsPanel:React.FC=()=>{
 const [balance,setBalance]=useState<CreatorBalanceSummary|null>(null); const [payouts,setPayouts]=useState<CreatorPayout[]>([]); const [amount,setAmount]=useState(''); const [loading,setLoading]=useState(true); const [submitting,setSubmitting]=useState(false);
 const load=useCallback(async()=>{setLoading(true);try{const [b,p]=await Promise.all([getCreatorBalance(),getCreatorPayouts()]);setBalance(b);setPayouts(p.payouts||[]);}catch(e:any){notifyToast(e?.message||'Payout data unavailable.','error');}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]);
 const submit=async()=>{if(!amount.trim())return;setSubmitting(true);try{await createCreatorPayout(amount);setAmount('');notifyToast('Payout requested.','success');await load();}catch(e:any){notifyToast(e?.message||'Payout request failed.','error');}finally{setSubmitting(false);}};
 return <section className="space-y-4">
  <div className="border-4 border-black bg-[var(--color-primary)] p-5 neo-shadow"><div className="font-mono text-[10px] font-black uppercase flex items-center gap-2"><Wallet className="w-4 h-4"/> V94 · PAYOUTS</div><h2 className="font-display font-black text-3xl sm:text-4xl uppercase mt-2">Vendor Balance + Payouts</h2><p className="font-mono text-[10px] mt-2 max-w-3xl">Server-authoritative earnings balance. Payouts are created against your verified seller account and reconciled with Razorpay Route.\</p></div>
  <div className="flex justify-end"><button onClick={()=>void load()} disabled={loading} className="border-2 border-black bg-white px-3 py-2 font-mono text-[9px] font-black uppercase"><RefreshCw className="inline w-3 h-3 mr-1"/>{loading?'LOADING':'REFRESH'}</button></div>
  <div className="grid sm:grid-cols-2 lg:grid-cols-5 gap-3">{[["TOTAL EARNED",balance?.totalEarnedPaise],["PENDING",balance?.pendingBalancePaise],["AVAILABLE",balance?.availableBalancePaise],["RESERVED",balance?.reservedBalancePaise],["PAID OUT",balance?.paidOutBalancePaise]].map(([label,v])=><div key={String(label)} className="border-2 border-black bg-white p-4"><div className="font-mono text-[8px] font-black uppercase">{label}</div><div className="font-display font-black text-2xl mt-2">{balance?inr(Number(v||0)):'—'}</div></div>)}</div>
  <div className="border-2 border-black bg-white p-5 space-y-3"><div className="font-display font-black uppercase flex items-center gap-2"><CircleDollarSign className="w-4 h-4"/> Withdrawable</div><div className="font-display font-black text-4xl">{balance?inr(balance.withdrawablePaise):'—'}</div>{balance && balance.payoutBlockedReason && <div className="border-2 border-black bg-neutral-100 p-3 font-mono text-[9px] uppercase">Payout status: {balance.payoutBlockedReason}</div>}<div className="grid sm:grid-cols-[1fr_auto] gap-2"><input value={amount} onChange={e=>setAmount(e.target.value)} placeholder="AMOUNT IN INR" inputMode="decimal" className="border-2 border-black px-3 py-3 font-mono text-sm" disabled={!balance?.payoutEnabled||submitting}/><button onClick={()=>void submit()} disabled={!balance?.payoutEnabled||submitting||!amount} className="border-2 border-black bg-[var(--color-primary)] px-5 py-3 font-mono text-[9px] font-black uppercase disabled:opacity-40">{submitting?'SUBMITTING':'WITHDRAW'}</button></div><div className="font-mono text-[8px] text-neutral-500 uppercase">Minimum: {balance?inr(balance.minimumPayoutPaise):'—'} · Funds move through the connected Razorpay seller account.</div></div>
  <div className="border-2 border-black bg-white p-4 font-mono text-[9px] flex gap-2 items-start"><ShieldCheck className="w-4 h-4 shrink-0"/><div><div className="font-black uppercase">SERVER-AUTHORITATIVE</div><div className="mt-1 text-neutral-600">Balance, eligibility, amount and payout destination are revalidated on the server. UI values cannot authorize a payout.</div></div></div>
  <div className="border-2 border-black bg-white p-5"><div className="font-display font-black uppercase mb-3">PAYOUT HISTORY</div><div className="space-y-2">{payouts.length===0?<div className="font-mono text-[9px] text-neutral-500">NO PAYOUTS YET.</div>:payouts.map(p=><div key={p.id} className="border-2 border-black p-3 grid sm:grid-cols-[1fr_auto_auto] gap-2 items-center"><div><div className="font-mono text-[8px] text-neutral-500">{p.requestedAt||p.createdAt}</div><div className="font-display font-black">{inr(p.amountPaise)}</div></div><div className="font-mono text-[9px] font-black uppercase">{p.status}</div><div className="font-mono text-[8px] text-neutral-500">{p.razorpayTransferId||'NO TRANSFER ID'}</div></div>)}</div></div>
 </section>
};
