import { ShareMenu } from './ShareMenu';
import React, { useEffect, useMemo, useState } from 'react';
import { Article, CreatorPageConfig, Series, CommunityUser, CommunityPost, PageView } from '../types';
import { getProfileByUsername, getPosts, getUserFollowing, followUser, unfollowUser } from '../lib/community';
import { getSeriesList } from '../lib/series';
import { ArrowRight, BookOpen, ExternalLink, Globe, Layers, Link2, MessageSquare, Package, Share2, UserCheck, UserPlus } from 'lucide-react';
import { VerifiedBadge } from './VerifiedBadge';
import { notifyToast } from '../lib/toast';
import { listPublicCreatorCommerceProducts, listUserEntitlements, type CommerceProduct, type CommercePublicPrice } from '../lib/commerce';
import { getMarketplaceProductsByIds, getSavedMarketplaceProductIds, toggleMarketplaceSave, recordMarketplaceEvent } from '../lib/marketplace';
import { MarketplaceProductCard } from './MarketplaceProductCard';
import { CommerceReportButton } from './CommerceReportButton';
import { getCreatorTrustSignals, getPublicCreatorTrustSignals } from '../lib/commerce';

interface Props { username: string; articles: Article[]; currentUserUid?: string; currentUsername?: string; onNavigate:(page:PageView,param?:string)=>void; }
const safeUrl=(v:string)=>{try{const u=new URL(v,window.location.origin);return ['http:','https:','mailto:'].includes(u.protocol)?u.href:''}catch{return ''}};
const dateValue=(s?:string)=>new Date(s||0).getTime()||0;
const articleAuthor=(a:Article)=>a.originalAuthor||a.author||{};

export const CreatorView:React.FC<Props>=({username,articles,currentUserUid,currentUsername,onNavigate})=>{
 const [profile,setProfile]=useState<CommunityUser|null>(null); const [trust,setTrust]=useState<any>(null); const [series,setSeries]=useState<Series[]>([]); const [posts,setPosts]=useState<CommunityPost[]>([]); const [products,setProducts]=useState<CommerceProduct[]>([]); const [productPrices,setProductPrices]=useState<Record<string,CommercePublicPrice|undefined>>({}); const [savedProducts,setSavedProducts]=useState<Set<string>>(new Set()); const [ownedProducts,setOwnedProducts]=useState<Set<string>>(new Set()); const [following,setFollowing]=useState(false); const [followBusy,setFollowBusy]=useState(false); const [loading,setLoading]=useState(true); const [tab,setTab]=useState<'featured'|'articles'|'series'|'posts'|'store'>('featured');
 useEffect(()=>{let active=true;recordMarketplaceEvent('creator_store_open','',{username});(async()=>{setLoading(true);try{const [p,s,pst]=await Promise.all([getProfileByUsername(username),getSeriesList(100),getPosts()]);if(!active)return;setProfile(p);setSeries(s);setPosts((pst as CommunityPost[]).filter(x=>x.authorUsername===username)); if(p?.uid){void getPublicCreatorTrustSignals(p.uid).then(setTrust).catch(()=>setTrust(null));} if(p?.uid){const store=await listPublicCreatorCommerceProducts(p.uid); if(active)setProducts(store); if(store.length){const detail=await getMarketplaceProductsByIds(store.map(x=>x.id)); if(active)setProductPrices(detail.prices||{});} if(currentUserUid){const [savedIds,ents]=await Promise.all([getSavedMarketplaceProductIds(currentUserUid).catch(()=>[]),listUserEntitlements(currentUserUid).catch(()=>[])]); if(active){setSavedProducts(new Set(savedIds));setOwnedProducts(new Set(ents.filter((e:any)=>e.status==='active'&&e.resourceType==='product').map((e:any)=>String(e.resourceId||''))));}}}if(currentUserUid&&p&&currentUserUid!==p.uid){const f=await getUserFollowing(currentUserUid);if(active)setFollowing(f.some(x=>x.uid===p.uid||x.username===p.username));}}catch(e){console.warn('Creator page load failed',e)}finally{if(active)setLoading(false)}})();return()=>{active=false}},[username,currentUserUid]);
 const authorArticles=useMemo(()=>articles.filter(a=>{const au=articleAuthor(a) as any;return au.uid===profile?.uid||au.username===profile?.username}).sort((a,b)=>dateValue(b.publishedAt)-dateValue(a.publishedAt)),[articles,profile]);
 if(loading)return <div className="max-w-6xl mx-auto px-4 py-24 text-center font-mono text-xs uppercase">LOADING CREATOR…</div>;
 if(!profile)return <div className="max-w-xl mx-auto px-4 py-24 text-center"><div className="border-4 border-black p-10 font-mono text-xs uppercase">CREATOR NOT FOUND</div></div>;
 const cfg=(profile.creatorPage||{}) as CreatorPageConfig; const hasCustomTheme=!!cfg.themeColor && cfg.themeColor.toUpperCase()!=='#000000'; const theme=hasCustomTheme?cfg.themeColor!:'#D97706'; const themeIsDefault=!hasCustomTheme;
 const ownSeries=series.filter(s=>s.ownerId===profile.uid||s.ownerUsername===profile.username).sort((a,b)=>dateValue(b.updatedAt)-dateValue(a.updatedAt));
 const featuredArticles=(cfg.featuredArticleSlugs||[]).map(id=>authorArticles.find(a=>a.slug===id)).filter(Boolean) as Article[];
 const featuredSeries=(cfg.featuredSeriesIds||[]).map(id=>ownSeries.find(s=>s.id===id)).filter(Boolean) as Series[];
 const featuredPosts=(cfg.featuredPostIds||[]).map(id=>posts.find(p=>p.id===id)).filter(Boolean) as CommunityPost[];
 const displayedArticles=featuredArticles.length?featuredArticles:authorArticles.slice(0,6); const displayedSeries=featuredSeries.length?featuredSeries:ownSeries.slice(0,4); const displayedPosts=featuredPosts.length?featuredPosts:posts.slice(0,4);
 const links=(cfg.customLinks||[]).map(l=>({...l,url:safeUrl(l.url),imageUrl:safeUrl(l.imageUrl||'')})).filter(l=>l.url);
 const socials=[['Website',profile.websiteUrl],['X',profile.socialX],['GitHub',profile.socialGithub],['Telegram',profile.socialTelegram],['Instagram',profile.socialInstagram]].map(([label,url])=>({label:String(label),url:safeUrl(String(url||''))})).filter(x=>x.url);
 const share=async()=>{const url=`${window.location.origin}/#creator/${profile.username}`;try{await navigator.clipboard.writeText(url);notifyToast('Creator page link copied.','success')}catch{notifyToast('Could not copy the creator link.','error')}};
 const toggleFollow=async()=>{if(!currentUserUid){notifyToast('Sign in to follow creators.','info');return}if(currentUserUid===profile.uid)return;setFollowBusy(true);try{if(following){await unfollowUser(currentUserUid,profile.uid);setFollowing(false);notifyToast(`Unfollowed @${profile.username}.`,'success')}else{await followUser(currentUserUid,profile.uid,profile.username,currentUsername||'');setFollowing(true);notifyToast(`Following @${profile.username}.`,'success')}}catch(e:any){notifyToast(e?.message||'Could not update follow.','error')}finally{setFollowBusy(false)}};
 const isEmpty=!authorArticles.length&&!ownSeries.length&&!posts.length&&!products.length;
 return <div className="min-h-screen" style={{'--creator-theme':theme} as any}>
  <div className="w-full max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-6 sm:py-10 space-y-6">
   <section className="border-4 border-black neo-shadow-lg overflow-hidden" style={{background:theme,color:themeIsDefault?'#000000':undefined}}>
    {cfg.coverImageUrl&&safeUrl(cfg.coverImageUrl)?<div className="h-40 sm:h-56 border-b-4 border-black overflow-hidden bg-black"><img src={cfg.coverImageUrl} alt="" className="w-full h-full object-cover"/></div>:null}
    <div className="p-6 sm:p-10"><div className="flex flex-col lg:flex-row lg:items-start lg:justify-between gap-7"><div className="flex items-start gap-4"><div className="shrink-0">{profile.photoURL?<img src={profile.photoURL} alt={profile.displayName} className="w-20 h-20 sm:w-28 sm:h-28 object-cover border-4 border-black bg-white"/>:<div className="w-20 h-20 sm:w-28 sm:h-28 border-4 border-black bg-white flex items-center justify-center font-display font-black text-4xl">{profile.displayName.charAt(0)}</div>}</div><div><div className="font-mono text-[10px] font-black uppercase">CREATOR PAGE</div><h1 className="font-display font-black text-4xl sm:text-6xl uppercase leading-[0.9] mt-1 break-words">{profile.displayName}<VerifiedBadge verified={profile.isVerified} color={profile.verificationColor} className="inline w-6 h-6 ml-2"/></h1><div className="font-mono text-xs mt-2">@{profile.username}</div><p className="font-mono text-xs uppercase mt-3">{cfg.tagline||profile.role||'Creator'}</p></div></div><div className="flex flex-wrap gap-2"><button onClick={toggleFollow} disabled={followBusy||currentUserUid===profile.uid} className="border-2 border-black bg-white px-4 py-2 font-mono text-[10px] font-black uppercase inline-flex items-center gap-2">{following?<><UserCheck className="w-4 h-4"/> FOLLOWING</>:<><UserPlus className="w-4 h-4"/> FOLLOW</>}</button><ShareMenu target={{type:'profile',username:profile.username}} title={profile.displayName} />
          <CommerceReportButton targetType="creator" targetId={profile.uid} />
</div></div>
     <div className="mt-7 max-w-4xl"><h2 className="font-display font-black text-3xl sm:text-5xl uppercase">{cfg.heroTitle||`Ideas by @${profile.username}`}</h2><p className="mt-3 text-sm sm:text-base whitespace-pre-wrap">{cfg.heroText||profile.bio||'Publishing on OFFSCRPT.'}</p></div>
     <div className="mt-5 flex flex-wrap gap-2 font-mono text-[9px] uppercase">{trust&&<><span className="border-2 border-black bg-white px-3 py-2"> {trust.trustedSeller?'TRUSTED SELLER':String(trust.trustStatus||'ACTIVE')}</span><span className="border-2 border-black bg-white px-3 py-2">{Number(trust.reviewCount||0)} REVIEWS</span><span className="border-2 border-black bg-white px-3 py-2">{Number(trust.averageRating||0).toFixed(1)} AVG RATING</span></>}</div><div className="mt-7 flex flex-wrap gap-2 font-mono text-[10px] uppercase"><span className="border-2 border-black bg-white px-3 py-2">{authorArticles.length} ARTICLES</span><span className="border-2 border-black bg-white px-3 py-2">{ownSeries.length} SERIES</span><span className="border-2 border-black bg-white px-3 py-2">{profile.followersCount||0} FOLLOWERS</span><span className="border-2 border-black bg-white px-3 py-2">{profile.followingCount||0} FOLLOWING</span></div>
    </div>
   </section>

   {(cfg.showSocialLinks??true)&&socials.length+links.length>0&&<section className="border-4 border-black bg-white p-4 sm:p-5"><div className="font-mono text-[10px] uppercase font-black">LINKS</div><div className="mt-3 flex flex-wrap gap-2">{[...socials.map(l=>({...l,imageUrl:''})),...links].map((l,i)=><a key={`${l.label}-${i}`} href={l.url} target={l.url.startsWith('http')?'_blank':undefined} rel={l.url.startsWith('http')?'noopener noreferrer':undefined} className="border-2 border-black px-3 py-2 bg-[var(--color-primary)] font-mono text-[10px] font-black uppercase inline-flex items-center gap-2">{l.imageUrl?<img src={l.imageUrl} alt="" className="w-5 h-5 object-cover border border-black bg-white"/>:<Link2 className="w-3 h-3"/>}{l.label}<ExternalLink className="w-3 h-3"/></a>)}</div></section>}

   <div className="border-4 border-black bg-black text-white p-2 flex flex-wrap gap-2">{(['featured','articles','series','posts','store'] as const).map(x=><button key={x} onClick={()=>setTab(x)} className={`px-4 py-2 border-2 border-black font-mono text-[10px] font-black uppercase ${tab===x?'bg-[var(--color-primary)] text-black':'bg-white text-black'}`}>{x==='store'?'STORE':x}</button>)}</div>

   {tab==='store'&&<section className="space-y-5"><div><div className="font-mono text-[10px] uppercase font-black">CREATOR STOREFRONT</div><h2 className="font-display font-black text-4xl uppercase">Products</h2></div>{products.length===0?<div className="border-4 border-black bg-white p-8 text-center font-mono text-xs uppercase">NO PUBLIC PRODUCTS YET.</div>:<div className={`grid gap-5 ${cfg.layout==='list'?'grid-cols-1':cfg.layout==='magazine'?'md:grid-cols-2':'sm:grid-cols-2 lg:grid-cols-3'}`}>{products.map(product=><MarketplaceProductCard key={product.id} product={product} price={productPrices[product.id]} owned={ownedProducts.has(product.id)} saved={savedProducts.has(product.id)} onOpen={(id)=>{recordMarketplaceEvent('product_open',id,{source:'creator-store'});onNavigate('product',id)}} onToggleSave={async(productToToggle)=>{try{const next=await toggleMarketplaceSave(productToToggle,savedProducts.has(productToToggle.id));setSavedProducts(prev=>{const n=new Set(prev);if(next)n.add(productToToggle.id);else n.delete(productToToggle.id);return n});notifyToast(next?'Saved product.':'Removed from saved products.','success');}catch(e:any){notifyToast(e?.message||'Could not save product.','error');}}}/>)}</div>}</section>}

   {tab==='featured'&&<div className="space-y-6">{(cfg.showAbout??true)&&<section className="border-4 border-black bg-white p-6"><div className="flex items-center gap-2 font-mono text-[10px] font-black uppercase"><Globe className="w-4 h-4"/>{cfg.aboutTitle||'ABOUT THE CREATOR'}</div><p className="mt-3 text-sm whitespace-pre-wrap">{profile.bio||cfg.heroText||'No bio published.'}</p></section>}
     {displayedSeries.length>0&&<section><SectionTitle label="Featured paths" title="Series" action="ALL SERIES →" onAction={()=>onNavigate('series')}/><ContentGrid layout={cfg.layout} items={displayedSeries.map(s=><button key={s.id} onClick={()=>onNavigate('series',s.id)} className="text-left border-4 border-black bg-[var(--color-secondary)] p-4 hover:-translate-y-1 transition-transform"><div className="font-mono text-[9px] uppercase"><Layers className="inline w-3 h-3"/> {s.articleCount||0} PARTS · {s.estimatedMinutes||0} MIN</div><h3 className="font-display font-black text-xl uppercase mt-1">{s.title}</h3><p className="text-sm mt-2 line-clamp-3">{s.description}</p></button>)} /></section>}
     {displayedArticles.length>0&&<section><SectionTitle label="Featured dispatches" title="Articles" action="VIEW ALL →" onAction={()=>onNavigate('blog')}/><ContentGrid layout={cfg.layout} items={displayedArticles.map(a=><button key={a.slug} onClick={()=>onNavigate('article',a.slug)} className="text-left border-4 border-black bg-white p-4 hover:bg-[var(--color-primary)]"><div className="font-mono text-[9px] uppercase">{a.category} · {a.readingTimeMinutes||0} MIN · {Number(a.viewsCount||0).toLocaleString()} VIEWS</div><h3 className="font-display font-black text-xl uppercase mt-1">{a.title}</h3><p className="text-sm mt-2 line-clamp-3">{a.excerpt}</p><div className="mt-4 font-mono text-[9px] font-black uppercase">READ <ArrowRight className="inline w-3 h-3"/></div></button>)} /></section>}
     {displayedPosts.length>0&&<section><SectionTitle label="Recent conversation" title="Posts" action="COMMUNITY →" onAction={()=>onNavigate('community')}/><div className="space-y-3">{displayedPosts.map(p=><button key={p.id} onClick={()=>onNavigate('community_post',p.id)} className="w-full text-left border-4 border-black bg-white p-4 hover:bg-[var(--color-secondary)]"><div className="font-mono text-[9px] uppercase"><MessageSquare className="inline w-3 h-3"/> {Number(p.viewsCount||0).toLocaleString()} VIEWS · @{p.authorUsername}</div><h3 className="font-display font-black text-xl uppercase mt-1">{p.title}</h3><p className="text-sm mt-1 line-clamp-2">{p.excerpt||p.content}</p></button>)}</div></section>}
   </div>}

   {tab==='articles'&&<ContentGrid layout={cfg.layout} items={displayedArticles.map(a=><button key={a.slug} onClick={()=>onNavigate('article',a.slug)} className="text-left border-4 border-black bg-white p-4 hover:bg-[var(--color-primary)]"><div className="font-mono text-[9px] uppercase">{a.category} · {a.readingTimeMinutes||0} MIN · {Number(a.viewsCount||0).toLocaleString()} VIEWS</div><h3 className="font-display font-black text-xl uppercase mt-1">{a.title}</h3><p className="text-sm mt-2 line-clamp-3">{a.excerpt}</p></button>)}/>} 
   {tab==='series'&&<ContentGrid layout={cfg.layout} items={displayedSeries.map(s=><button key={s.id} onClick={()=>onNavigate('series',s.id)} className="text-left border-4 border-black bg-[var(--color-secondary)] p-4"><div className="font-mono text-[9px] uppercase">{s.articleCount||0} PARTS</div><h3 className="font-display font-black text-xl uppercase mt-1">{s.title}</h3><p className="text-sm mt-2">{s.description}</p></button>)}/>} 
   {tab==='posts'&&<div className="space-y-3">{displayedPosts.map(p=><button key={p.id} onClick={()=>onNavigate('community_post',p.id)} className="w-full text-left border-4 border-black bg-white p-4"><div className="font-mono text-[9px] uppercase">{Number(p.viewsCount||0).toLocaleString()} VIEWS</div><h3 className="font-display font-black text-xl uppercase mt-1">{p.title}</h3><p className="text-sm mt-2">{p.excerpt||p.content}</p></button>)}</div>}
   {isEmpty&&<div className="border-4 border-dashed border-black p-12 text-center"><BookOpen className="w-10 h-10 mx-auto"/><div className="font-display font-black text-2xl uppercase mt-3">Nothing published yet</div><p className="font-mono text-xs text-neutral-500 mt-2">This creator has not published public content.</p></div>}
  </div>
 </div>;
};

const SectionTitle=({label,title,action,onAction}:{label:string;title:string;action:string;onAction:()=>void})=><div className="flex items-end justify-between gap-3 mb-3"><div><div className="font-mono text-[9px] uppercase">{label}</div><h2 className="font-display font-black text-2xl uppercase">{title}</h2></div><button onClick={onAction} className="font-mono text-[9px] font-black uppercase underline">{action}</button></div>;
const ContentGrid=({items,layout='grid'}:{items:React.ReactNode[];layout?:CreatorPageConfig['layout']})=><div className={`grid gap-4 ${layout==='list'?'grid-cols-1':layout==='magazine'?'md:grid-cols-2':'md:grid-cols-2 lg:grid-cols-3'}`}>{items}</div>;
