import React, { useEffect, useState } from 'react';
import { ShieldCheck, Star, UserRound } from 'lucide-react';
import { getCreatorTrustSignals } from '../lib/commerce';
import { notifyToast } from '../lib/toast';
export const CreatorTrustPanel:React.FC<{creatorId:string}>=({creatorId})=>{
 const [signal,setSignal]=useState<any>(null); const [loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;setLoading(true);void getCreatorTrustSignals(creatorId).then(x=>{if(active)setSignal(x);}).catch((e:any)=>{if(active)notifyToast(e?.message||'Trust information unavailable.','error');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[creatorId]);
 return <section className="border-4 border-black bg-white shadow-[7px_7px_0_#000] p-5 sm:p-7"><div className="font-mono text-[9px] font-black text-neutral-500 uppercase flex items-center gap-2"><ShieldCheck className="w-4 h-4"/>SELLER TRUST</div><h2 className="font-display font-black text-3xl uppercase mt-1">TRUST SIGNALS</h2>{loading?<div className="mt-5 font-mono text-[9px]">LOADING…</div>:signal?<><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-2 mt-5"><div className="border-2 border-black p-3"><UserRound className="w-4 h-4"/><div className="font-mono text-[8px] font-black mt-2">STATUS</div><div className="font-display font-black text-xl uppercase">{signal.trustStatus}</div></div><div className="border-2 border-black p-3"><Star className="w-4 h-4"/><div className="font-mono text-[8px] font-black mt-2">AVERAGE RATING</div><div className="font-display font-black text-xl">{(Number.isFinite(Number(signal.averageRating))?Number(signal.averageRating):0).toFixed(1)}</div></div><div className="border-2 border-black p-3"><div className="font-mono text-[8px] font-black">PUBLISHED REVIEWS</div><div className="font-display font-black text-xl mt-2">{signal.reviewCount||0}</div></div><div className="border-2 border-black p-3"><div className="font-mono text-[8px] font-black">VERIFIED REVIEWS</div><div className="font-display font-black text-xl mt-2">{signal.verifiedReviewCount||0}</div></div></div><div className="mt-4 border-2 border-black p-3 font-mono text-[8px]">{signal.trustedSeller?'DETERMINISTIC TRUST SIGNAL: TRUSTED SELLER':'TRUST STATUS IS DETERMINISTIC AND BASED ON SELLER STATE + PUBLISHED VERIFIED-REVIEW SIGNALS.'}</div></>:<div className="mt-5 border-2 border-dashed border-black p-4 font-mono text-[9px] text-neutral-500">TRUST DATA UNAVAILABLE.</div>}</section>;
};
