import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Flag, Pencil, Star, Trash2 } from 'lucide-react';
import { auth, loginWithGoogle } from '../lib/firebase';
import { createCommerceReview, getCommerceTrustSignals, getProductReviews, getReviewEligibility, getMyCommerceReviews, removeCommerceReview, updateCommerceReview, type CommerceReview, type CommerceReviewAggregate, type CommerceReviewEligibility, type CommerceTrustSignals } from '../lib/commerce';
import { notifyToast } from '../lib/toast';
import { CommerceReportButton } from './CommerceReportButton';
import type { CommunityUser } from '../types';

const Stars:React.FC<{value:number;large?:boolean}>=({value,large})=><div className={`flex items-center gap-0.5 ${large?'text-lg':''}`} aria-label={`${value} out of 5 stars`}>{[1,2,3,4,5].map(n=><Star key={n} className={`w-4 h-4 ${n<=Math.round(value)?'fill-current':''}`}/>)}</div>;
const emptyAgg:CommerceReviewAggregate={productId:'',reviewCount:0,averageRating:0,rating1Count:0,rating2Count:0,rating3Count:0,rating4Count:0,rating5Count:0,verifiedReviewCount:0};
export const ProductReviewsSection:React.FC<{productId:string;userProfile:CommunityUser|null}>=({productId,userProfile})=>{
  const [aggregate,setAggregate]=useState<CommerceReviewAggregate>(emptyAgg); const [reviews,setReviews]=useState<CommerceReview[]>([]); const [nextCursor,setNextCursor]=useState<string|null>(null); const [loadingMore,setLoadingMore]=useState(false); const [ownedReviewIds,setOwnedReviewIds]=useState<Set<string>>(new Set()); const [trust,setTrust]=useState<CommerceTrustSignals|null>(null); const [eligibility,setEligibility]=useState<CommerceReviewEligibility|null>(null); const [sort,setSort]=useState<'recent'|'highest'|'lowest'|'verified'>('recent'); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [formOpen,setFormOpen]=useState(false); const [editing,setEditing]=useState<CommerceReview|null>(null); const [rating,setRating]=useState(5); const [title,setTitle]=useState(''); const [body,setBody]=useState('');
  const load=useCallback(async()=>{setLoading(true);try{const [r,t]=await Promise.all([getProductReviews(productId,{sort,limit:20}),getCommerceTrustSignals(productId)]);setReviews(r.reviews||[]);setNextCursor(r.nextCursor||null);setAggregate(r.aggregate||emptyAgg);setTrust(t);if(userProfile?.uid){try{const mine=await getMyCommerceReviews(productId);setOwnedReviewIds(new Set((mine.reviews||[]).filter(x=>x.productId===productId).map(x=>x.id)));}catch{setOwnedReviewIds(new Set());}}else setOwnedReviewIds(new Set());}catch(e:any){notifyToast(e?.message||'Reviews unavailable.','error');}finally{setLoading(false);}},[productId,sort,userProfile?.uid]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{if(userProfile?.uid){void getReviewEligibility(productId).then(setEligibility).catch(()=>setEligibility(null));}else setEligibility(null);},[productId,userProfile?.uid]);
  const totalDist=aggregate.reviewCount||0; const resetForm=()=>{setFormOpen(false);setEditing(null);setRating(5);setTitle('');setBody('');};
  const startEdit=(review:CommerceReview)=>{setEditing(review);setRating(review.rating);setTitle(review.title||'');setBody(review.body||'');setFormOpen(true);};
  const submit=async()=>{if(!auth.currentUser){try{if(!(await loginWithGoogle()))return;}catch(e:any){notifyToast(e?.message||'Sign-in failed.','error');return;}} setBusy(true);try{if(editing)await updateCommerceReview({reviewId:editing.id,rating,title,body});else await createCommerceReview({productId,rating,title,body});notifyToast(editing?'Review updated and queued for moderation.':'Review submitted for moderation.','success');resetForm();await load();void getReviewEligibility(productId).then(setEligibility).catch(()=>{});}catch(e:any){notifyToast(e?.message||'Could not save review.','error');}finally{setBusy(false);}};
  const remove=async(review:CommerceReview)=>{if(!window.confirm('Remove your review? The moderation history will be preserved.'))return;setBusy(true);try{await removeCommerceReview(review.id);notifyToast('Review removed.','success');await load();}catch(e:any){notifyToast(e?.message||'Could not remove review.','error');}finally{setBusy(false);}};
  const loadMore=async()=>{if(!nextCursor||loadingMore)return;setLoadingMore(true);try{const r=await getProductReviews(productId,{sort,limit:20,cursor:nextCursor});setReviews(prev=>[...prev,...(r.reviews||[])]);setNextCursor(r.nextCursor||null);setAggregate(r.aggregate||emptyAgg);}catch(e:any){notifyToast(e?.message||'Could not load more reviews.','error');}finally{setLoadingMore(false);}};
  const canWrite=Boolean(userProfile && eligibility?.eligible); const bars=useMemo(()=>[5,4,3,2,1].map(n=>({n,count:Number((aggregate as any)[`rating${n}Count`]||0),width:totalDist?Math.round(Number((aggregate as any)[`rating${n}Count`]||0)/totalDist*100):0})),[aggregate,totalDist]);
  return <section className="border-4 border-black bg-white shadow-[7px_7px_0_#000] p-5 sm:p-7">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="font-mono text-[9px] font-black text-neutral-500 uppercase">TRUST & REVIEWS</div><h2 className="font-display font-black text-3xl sm:text-4xl uppercase mt-1">CUSTOMER REVIEWS</h2><div className="mt-3 flex flex-wrap items-center gap-3"><Stars value={aggregate.averageRating} large/><span className="font-display font-black text-2xl">{aggregate.averageRating.toFixed(1)}</span><span className="font-mono text-[9px] text-neutral-500 uppercase">{aggregate.reviewCount} published · {aggregate.verifiedReviewCount} verified</span></div></div><CommerceReportButton targetType="product" targetId={productId} label="REPORT PRODUCT"/></div>
    {trust&&<div className="mt-4 flex flex-wrap gap-2 text-[8px] font-mono font-black uppercase"><span className="border-2 border-black bg-[var(--color-primary)] px-2 py-1">{trust.productPublished?'PRODUCT PUBLISHED':'NOT PUBLISHED'}</span>{trust.trustedSeller&&<span className="border-2 border-black bg-white px-2 py-1">TRUSTED SELLER</span>}<span className="border-2 border-black bg-white px-2 py-1">{trust.verifiedReviewCount} VERIFIED REVIEWS</span></div>}
    <div className="grid lg:grid-cols-[240px_1fr] gap-5 mt-6"><div className="border-2 border-black p-4 space-y-3">{bars.map(x=><div key={x.n} className="grid grid-cols-[32px_1fr_32px] items-center gap-2 font-mono text-[9px]"><span>{x.n}★</span><div className="h-3 border-2 border-black bg-neutral-100"><div className="h-full bg-black" style={{width:`${x.width}%`}}/></div><span className="text-right">{x.count}</span></div>)}</div>
      <div className="space-y-3"><div className="flex flex-wrap items-center justify-between gap-2"><div className="font-mono text-[9px] font-black uppercase">{loading?'LOADING REVIEWS…':`${reviews.length} SHOWN`}</div><select value={sort} onChange={e=>setSort(e.target.value as any)} className="border-2 border-black px-3 py-2 font-mono text-[8px] font-black uppercase"><option value="recent">Most recent</option><option value="highest">Highest rated</option><option value="lowest">Lowest rated</option><option value="verified">Verified purchase</option></select></div>
        {canWrite&&!formOpen&&<button onClick={()=>setFormOpen(true)} className="w-full border-2 border-black bg-[var(--color-primary)] px-4 py-3 font-mono text-[9px] font-black uppercase">WRITE A REVIEW · VERIFIED PURCHASE</button>}
        {!userProfile&&<div className="border-2 border-dashed border-black p-4 font-mono text-[9px] text-neutral-500">SIGN IN AND PURCHASE THIS PRODUCT TO WRITE A VERIFIED REVIEW.</div>}
        {userProfile&&eligibility&&!eligibility.eligible&&eligibility.reason==='PURCHASE_REQUIRED'&&!Array.from(ownedReviewIds).some(id=>reviews.some(r=>r.id===id))&&<div className="border-2 border-dashed border-black p-4 font-mono text-[9px] text-neutral-500">REVIEWS REQUIRE AN ELIGIBLE PURCHASE OF THIS PRODUCT.</div>}
        {formOpen&&<div className="border-2 border-black p-4 bg-neutral-50"><div className="font-mono text-[9px] font-black uppercase">{editing?'EDIT REVIEW':'WRITE REVIEW'}</div><div className="flex gap-1 mt-3">{[1,2,3,4,5].map(n=><button key={n} type="button" aria-label={`${n} stars`} onClick={()=>setRating(n)} className="p-1"><Star className={`w-6 h-6 ${n<=rating?'fill-current':''}`}/></button>)}</div><input value={title} onChange={e=>setTitle(e.target.value.slice(0,120))} placeholder="Title (optional)" className="mt-3 w-full border-2 border-black px-3 py-3 text-sm"/><textarea value={body} onChange={e=>setBody(e.target.value.slice(0,5000))} placeholder="What did you think?" rows={5} className="mt-2 w-full border-2 border-black p-3 text-sm"/><div className="flex items-center justify-between font-mono text-[8px] text-neutral-500 mt-1"><span>{body.length}/5000</span><span><CheckCircle2 className="inline w-3 h-3 mr-1"/>VERIFIED PURCHASE DERIVED SERVER-SIDE</span></div><div className="flex gap-2 mt-3"><button onClick={()=>void submit()} disabled={busy||!body.trim()} className="border-2 border-black bg-[var(--color-primary)] px-4 py-2 font-mono text-[9px] font-black uppercase disabled:opacity-40">{busy?'SAVING…':'SUBMIT'}</button><button onClick={resetForm} disabled={busy} className="border-2 border-black px-4 py-2 font-mono text-[9px] font-black uppercase">CANCEL</button></div></div>}
        {reviews.length===0&&!loading&&<div className="border-2 border-dashed border-black p-7 text-center font-mono text-[9px] text-neutral-500 uppercase">NO PUBLISHED REVIEWS YET.</div>}
        {reviews.map(review=><article key={review.id} className="border-2 border-black p-4"><div className="flex flex-wrap justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-[10px] font-black uppercase">{review.reviewerDisplayName||'OFFSCRPT USER'}</span>{review.verifiedPurchase&&<span className="border border-black px-1 py-0.5 font-mono text-[7px] font-black uppercase bg-[var(--color-primary)]">VERIFIED PURCHASE</span>}</div><div className="mt-1"><Stars value={review.rating}/></div></div><div className="flex items-center gap-2"><span className="font-mono text-[8px] text-neutral-500">{review.createdAt?new Date(review.createdAt).toLocaleDateString():''}</span>{ownedReviewIds.has(review.id)&&<><button aria-label="Edit review" onClick={()=>startEdit(review)} className="border border-black p-2"><Pencil className="w-3 h-3"/></button><button aria-label="Remove review" onClick={()=>void remove(review)} className="border border-black p-2"><Trash2 className="w-3 h-3"/></button></>}{!ownedReviewIds.has(review.id)&&<CommerceReportButton targetType="review" targetId={review.id} label="REPORT"/>}</div></div>{review.title&&<h3 className="font-display font-black text-xl uppercase mt-3">{review.title}</h3>}<p className="text-sm leading-6 whitespace-pre-wrap mt-2">{review.body}</p></article>)}
        {nextCursor&&<button type="button" onClick={()=>void loadMore()} disabled={loadingMore} className="w-full border-2 border-black px-4 py-3 font-mono text-[9px] font-black uppercase">{loadingMore?'LOADING…':'LOAD MORE REVIEWS'}</button>}
      </div>
    </div>
  </section>;
};
