import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, Eye, Flag, RefreshCw, Search, ShieldCheck, XCircle } from 'lucide-react';
import { adminGetModerationCase, adminGetModerationQueue, adminModerationAction, adminSearchModeration, getTrustHealth, rebuildReviewAggregate, validateReviewAggregates, type CommerceModerationCase, type CommerceModerationAction, type CommerceReport } from '../lib/commerce';
import { notifyToast } from '../lib/toast';

const statuses=['queued','under_review','escalated','resolved','dismissed'];
const priorities=['normal','high','critical','low'];
const types=['','review','product','creator'];
const destructive=new Set(['hide','remove','restrict','suspend']);
export const TrustModerationAdminPanel:React.FC=()=>{
  const [cases,setCases]=useState<CommerceModerationCase[]>([]); const [selectedId,setSelectedId]=useState(''); const [detail,setDetail]=useState<{case:CommerceModerationCase;reports:CommerceReport[];target:any;actions:CommerceModerationAction[]}|null>(null); const [status,setStatus]=useState('queued'); const [priority,setPriority]=useState(''); const [type,setType]=useState(''); const [assignedTo,setAssignedTo]=useState(''); const [search,setSearch]=useState(''); const [searchResults,setSearchResults]=useState<any[]>([]); const [health,setHealth]=useState<any>(null); const [loading,setLoading]=useState(false); const [actionBusy,setActionBusy]=useState(false); const [reason,setReason]=useState('policy_violation'); const [notes,setNotes]=useState(''); const [assignId,setAssignId]=useState(''); const [aggregateProductId,setAggregateProductId]=useState(''); const [aggregateCheck,setAggregateCheck]=useState<any>(null);
  const load=useCallback(async()=>{setLoading(true);try{const r=await adminGetModerationQueue({status,priority,targetType:type,assignedTo,limit:50});setCases(r.cases||[]);}catch(e:any){notifyToast(e?.message||'Moderation queue unavailable.','error');}finally{setLoading(false);}},[status,priority,type,assignedTo]);
  const openCase=async(id:string)=>{setSelectedId(id);try{const d=await adminGetModerationCase(id);setDetail(d);}catch(e:any){notifyToast(e?.message||'Could not open case.','error');}};
  useEffect(()=>{void load();},[load]);
  const refreshHealth=async()=>{try{setHealth(await getTrustHealth());}catch(e:any){notifyToast(e?.message||'Trust health unavailable.','error');}};
  const doAction=async(action:string,targetType:string,targetId:string,caseId?:string)=>{if(destructive.has(action)&&!window.confirm(`Confirm ${action.toUpperCase()} for ${targetType} ${targetId}?`))return; if(['resolve','dismiss','escalate','assign','unassign'].includes(action)&&!caseId)return; setActionBusy(true);try{const result=await adminModerationAction({action,targetType,targetId,caseId,reasonCode:reason,notes,assignedTo:action==='assign'?assignId:undefined,requestId:crypto.randomUUID()});notifyToast(`Moderation action ${action.replaceAll('_',' ')} completed.`,'success');if(caseId)await openCase(caseId);await load();return result;}catch(e:any){notifyToast(e?.message||'Moderation action failed.','error');}finally{setActionBusy(false);}};
  const runSearch=async()=>{if(!search.trim()){setSearchResults([]);return;}setLoading(true);try{const r=await adminSearchModeration(search);setSearchResults(r.results||[]);}catch(e:any){notifyToast(e?.message||'Moderation search failed.','error');}finally{setLoading(false);}};
  const checkAggregate=async()=>{if(!aggregateProductId.trim())return;try{setAggregateCheck(await validateReviewAggregates(aggregateProductId.trim()));}catch(e:any){notifyToast(e?.message||'Aggregate validation failed.','error');}};
  const repairAggregate=async()=>{if(!aggregateProductId.trim())return;if(!window.confirm('Explicitly rebuild this product review aggregate?'))return;try{await rebuildReviewAggregate(aggregateProductId.trim(),true,crypto.randomUUID());notifyToast('Review aggregate rebuilt and audited.','success');await checkAggregate();}catch(e:any){notifyToast(e?.message||'Aggregate rebuild failed.','error');}};
  const overview=useMemo(()=>({pending:cases.filter(c=>c.status==='queued').length,review:cases.filter(c=>c.targetType==='review').length,high:cases.filter(c=>c.priority==='high'||c.priority==='critical').length}),[cases]);
  return <section className="border-4 border-black bg-white shadow-[7px_7px_0_#000] p-5 sm:p-7 space-y-5">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><div className="font-mono text-[9px] font-black text-neutral-500 uppercase flex items-center gap-2"><ShieldCheck className="w-4 h-4"/>V96 TRUST & MODERATION</div><h2 className="font-display font-black text-3xl sm:text-4xl uppercase mt-1">Trust Control Center</h2><p className="font-mono text-[9px] text-neutral-500 mt-2 max-w-3xl">Server-authoritative moderation queue, review enforcement, trust health and audit history. Reports are evidence for review, not automatic proof of a violation.</p></div><button onClick={()=>void load()} className="border-2 border-black px-3 py-2 font-mono text-[8px] font-black uppercase"><RefreshCw className="inline w-3 h-3 mr-1"/>{loading?'LOADING':'REFRESH'}</button></header>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-2">{[['OPEN CASES',cases.filter(c=>!['resolved','dismissed'].includes(c.status)).length],['PENDING',overview.pending],['REVIEW CASES',overview.review],['HIGH PRIORITY',overview.high]].map(([l,v])=><div key={String(l)} className="border-2 border-black p-4"><div className="font-mono text-[8px] font-black uppercase">{l}</div><div className="font-display font-black text-3xl mt-1">{v}</div></div>)}</div>
    <div className="border-2 border-black p-4 flex flex-wrap gap-2 items-center"><select value={status} onChange={e=>setStatus(e.target.value)} className="border-2 border-black px-2 py-2 font-mono text-[8px] font-black uppercase"><option value="">ALL STATUS</option>{statuses.map(x=><option key={x}>{x}</option>)}</select><select value={priority} onChange={e=>setPriority(e.target.value)} className="border-2 border-black px-2 py-2 font-mono text-[8px] font-black uppercase"><option value="">ALL PRIORITY</option>{priorities.map(x=><option key={x}>{x}</option>)}</select><select value={type} onChange={e=>setType(e.target.value)} className="border-2 border-black px-2 py-2 font-mono text-[8px] font-black uppercase">{types.map(x=><option key={x} value={x}>{x||'ALL TARGETS'}</option>)}</select><input value={assignedTo} onChange={e=>setAssignedTo(e.target.value)} placeholder="ASSIGNEE ID" className="border-2 border-black px-3 py-2 font-mono text-[8px] flex-1 min-w-[140px]"/><div className="ml-auto flex gap-2"><button onClick={()=>void refreshHealth()} className="border-2 border-black bg-[var(--color-primary)] px-3 py-2 font-mono text-[8px] font-black uppercase">CHECK TRUST HEALTH</button></div></div>
    {health&&<div className={`border-2 border-black p-4 ${health.status==='critical'?'bg-red-100':health.status==='warning'?'bg-yellow-100':'bg-[var(--color-primary)]'}`}><div className="flex items-center gap-2 font-mono text-[9px] font-black uppercase">{health.status==='healthy'?<CheckCircle2 className="w-4 h-4"/>:<AlertTriangle className="w-4 h-4"/>} TRUST HEALTH: {health.status}</div><div className="font-mono text-[8px] mt-2">{health.critical} critical · {health.warnings} warnings · checked {health.checkedAt?new Date(health.checkedAt).toLocaleString():''}</div>{health.issues?.slice(0,6).map((i:any,idx:number)=><div key={idx} className="font-mono text-[8px] mt-1">{i.severity.toUpperCase()} · {i.type} · {i.entityId}</div>)}</div>}
    <div className="grid lg:grid-cols-[minmax(0,1fr)_minmax(0,1.35fr)] gap-5"><div className="border-2 border-black"><div className="p-3 border-b-2 border-black font-mono text-[9px] font-black uppercase">MODERATION QUEUE</div><div className="max-h-[620px] overflow-auto">{cases.length===0?<div className="p-6 font-mono text-[9px] text-neutral-500">NO CASES MATCH CURRENT FILTERS.</div>:cases.map(c=><button key={c.id} onClick={()=>void openCase(c.id)} className={`block w-full text-left p-3 border-b-2 border-black ${selectedId===c.id?'bg-[var(--color-primary)]':'bg-white'}`}><div className="flex justify-between gap-2"><span className="font-mono text-[8px] font-black uppercase">{c.priority} · {c.status}</span><span className="font-mono text-[7px] text-neutral-500">{c.createdAt?new Date(c.createdAt).toLocaleDateString():''}</span></div><div className="font-display font-black uppercase mt-1">{c.targetType}</div><div className="font-mono text-[8px] mt-1 truncate">{c.targetId}</div><div className="font-mono text-[7px] text-neutral-500 mt-1">REPORTS {c.reportCount||c.reportIds?.length||0} · {c.assignedTo?'ASSIGNED':'UNASSIGNED'}</div></button>)}</div></div>
      <div className="border-2 border-black p-4 min-h-[400px]">{!detail?<div className="h-full flex items-center justify-center text-center font-mono text-[9px] text-neutral-500"><Eye className="w-5 h-5 mr-2"/>SELECT A CASE TO INSPECT</div>:<div className="space-y-4"><div className="flex flex-wrap justify-between gap-3"><div><div className="font-mono text-[9px] font-black uppercase">CASE {detail.case.id}</div><div className="font-display text-2xl font-black uppercase mt-1">{detail.case.targetType} · {detail.case.status}</div><div className="font-mono text-[8px] text-neutral-500 mt-1">PRIORITY {detail.case.priority} · ASSIGNEE {detail.case.assignedTo||'NONE'}</div></div><div className="flex flex-wrap gap-1">{detail.case.status!=='resolved'&&<button disabled={actionBusy} onClick={()=>void doAction('resolve',detail.case.targetType,detail.case.targetId,detail.case.id)} className="border-2 border-black bg-[var(--color-primary)] px-2 py-2 font-mono text-[8px] font-black">RESOLVE</button>}{detail.case.status!=='dismissed'&&<button disabled={actionBusy} onClick={()=>void doAction('dismiss',detail.case.targetType,detail.case.targetId,detail.case.id)} className="border-2 border-black px-2 py-2 font-mono text-[8px] font-black">DISMISS</button>}<button disabled={actionBusy} onClick={()=>void doAction('escalate',detail.case.targetType,detail.case.targetId,detail.case.id)} className="border-2 border-black px-2 py-2 font-mono text-[8px] font-black">ESCALATE</button></div></div>
          <div className="border-2 border-black p-3"><div className="font-mono text-[8px] font-black uppercase">TARGET</div><pre className="whitespace-pre-wrap break-words text-[10px] mt-2">{JSON.stringify(detail.target,null,2)}</pre></div>
          <div className="border-2 border-black p-3"><div className="font-mono text-[8px] font-black uppercase">REPORTS ({detail.reports.length})</div>{detail.reports.map(r=><div key={r.id} className="border-t border-black mt-2 pt-2"><div className="font-mono text-[8px] font-black">{r.reasonCode} · {r.status}</div><div className="text-xs mt-1">{r.description||'No details.'}</div></div>)}</div>
          <div className="border-2 border-black p-3"><div className="font-mono text-[8px] font-black uppercase">ACTIONS</div>{detail.actions.map(a=><div key={a.id} className="border-t border-black mt-2 pt-2 font-mono text-[8px]"><div>{a.action} · {a.actorRole} · {a.reasonCode}</div><div className="text-neutral-500">{a.previousState||'—'} → {a.newState||'—'} · {a.timestamp?new Date(a.timestamp).toLocaleString():''}</div></div>)}</div>
          <div className="border-2 border-black p-3"><div className="font-mono text-[8px] font-black uppercase">ACTION CONTROLS</div><select value={reason} onChange={e=>setReason(e.target.value)} className="mt-2 border-2 border-black px-2 py-2 font-mono text-[8px] font-black uppercase"><option value="policy_violation">policy violation</option><option value="spam">spam</option><option value="harassment">harassment</option><option value="fake_review">fake review</option><option value="copyright">copyright</option><option value="prohibited_content">prohibited content</option><option value="misleading_content">misleading content</option><option value="other">other</option></select><textarea value={notes} onChange={e=>setNotes(e.target.value.slice(0,3000))} rows={3} placeholder="Internal moderator notes" className="mt-2 w-full border-2 border-black p-2 text-xs"/><div className="flex flex-wrap gap-2 mt-2">{detail.case.targetType==='review'&&<>{['published','hidden','removed'].map(a=><button key={a} disabled={actionBusy} onClick={()=>void doAction(a,'review',detail.case.targetId,detail.case.id)} className="border-2 border-black px-3 py-2 font-mono text-[8px] font-black uppercase">{a}</button>)}</>}{detail.case.targetType==='product'&&<>{['approve','hide','remove','restore','restrict'].map(a=><button key={a} disabled={actionBusy} onClick={()=>void doAction(a,'product',detail.case.targetId,detail.case.id)} className="border-2 border-black px-3 py-2 font-mono text-[8px] font-black uppercase">{a}</button>)}</>}{detail.case.targetType==='creator'&&<>{['approve','restrict','suspend','restore'].map(a=><button key={a} disabled={actionBusy} onClick={()=>void doAction(a,'creator',detail.case.targetId,detail.case.id)} className="border-2 border-black px-3 py-2 font-mono text-[8px] font-black uppercase">{a}</button>)}</>}
            <input value={assignId} onChange={e=>setAssignId(e.target.value)} placeholder="MODERATOR ID" className="border-2 border-black px-2 py-2 font-mono text-[8px] flex-1"/><button disabled={actionBusy||!assignId} onClick={()=>void doAction('assign',detail.case.targetType,detail.case.targetId,detail.case.id)} className="border-2 border-black px-3 py-2 font-mono text-[8px] font-black">ASSIGN</button><button disabled={actionBusy} onClick={()=>void doAction('unassign',detail.case.targetType,detail.case.targetId,detail.case.id)} className="border-2 border-black px-3 py-2 font-mono text-[8px] font-black">UNASSIGN</button></div></div>
        </div>}
      </div></div>
    <div className="border-2 border-black p-4"><div className="font-mono text-[8px] font-black uppercase flex items-center gap-2"><Search className="w-3 h-3"/>SERVER-SIDE MODERATION SEARCH</div><div className="flex gap-2 mt-2"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="review / case / report / creator / product / order ID" className="flex-1 border-2 border-black px-3 py-2 font-mono text-[8px]"/><button onClick={()=>void runSearch()} className="border-2 border-black bg-black text-white px-3 py-2 font-mono text-[8px] font-black">SEARCH</button></div>{searchResults.length>0&&<div className="mt-3 space-y-1">{searchResults.slice(0,20).map((r:any)=><div key={`${r.collection}:${r.id}`} className="border border-black p-2 font-mono text-[8px]"><span className="font-black">{r.collection}</span> · {r.id} · {r.targetType||''} · {r.status||''}</div>)}</div>}</div>
    <div className="border-2 border-black p-4"><div className="font-mono text-[8px] font-black uppercase">REVIEW AGGREGATE INTEGRITY</div><div className="flex flex-wrap gap-2 mt-2"><input value={aggregateProductId} onChange={e=>setAggregateProductId(e.target.value)} placeholder="PRODUCT ID" className="border-2 border-black px-3 py-2 font-mono text-[8px] flex-1 min-w-[180px]"/><button onClick={()=>void checkAggregate()} className="border-2 border-black px-3 py-2 font-mono text-[8px] font-black">VALIDATE</button><button onClick={()=>void repairAggregate()} className="border-2 border-black bg-[var(--color-primary)] px-3 py-2 font-mono text-[8px] font-black">REPAIR (EXPLICIT)</button></div>{aggregateCheck&&<div className="mt-3 font-mono text-[8px]">{aggregateCheck.healthy?'HEALTHY':'MISMATCH DETECTED'} · expected {JSON.stringify(aggregateCheck.expected)} · actual {JSON.stringify(aggregateCheck.actual)}</div>}</div>
  </section>;
};
